### ISSUE TITLE
Bug - find command doesnt work properly

### ISSUE THREAD

**Issue by majunting** [PhaseBT14A2/addressbook-level4#104]
![image](https://user-images.githubusercontent.com/19281947/32362957-c79e5c5a-c0a7-11e7-8566-f02c56226c44.png)
unable to find person by name without prefix

**Comment by kaiyu92** [comment]
Hi

As we did some enhancement to the find features for both address book and event book, we forgot to update the user guide. Currently, the find requires an attribute/prefix attached. Reason being is we want the user to be able to narrow down the contacts/events easily. 

**Previous Find Function:**
The previous Find feature requires a valid keyword, which means if I want to find Bernice Yu, I must type a keyword like `bernice` or `Yu`.
E.g. find n/bernice 
returns any person who have name `bernice` in it

E.g. findevent et/basketball
returns any events which have title `basketball` in it

**Current Find Function:**
The current find feature requires a sequence of the word, which means if I want to find Bernice Yu, I can type `ber`, `nice`, or `ern.
E.g. find n/ber
returns any person whose name contain a sequence of `ber`

E.g. findevent et/ball
returns any events whose title contain a sequence of `ball`

Sorry for the unclear instructions in our user guide. I have make the follow-up in our user guide.

Thank you.

Regards,
Quek Kai Yu
